# Generated by Django 3.1.4 on 2020-12-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_rereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.review'),
        ),
    ]
