"""
Django settings for mysite3 project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os, environ

from pathlib import Path

env = environ.Env(
    DEBUG=(bool, False),
)  # 기본 값
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# env.read_env(env.str("ENV_PATH", ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party apps
    "bootstrap4",
    "debug_toolbar",  # FIXME: 개발모드에서만 추가해야함
    "django_extensions",
    "taggit",
    "taggit_templatetags2",
    "django_summernote",
    "django_static_fontawesome",
    "storages",
    # locals apps
    "accounts",
    "journal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # debug_toolbar
]

ROOT_URLCONF = "mysite3.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "mysite3" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite3.wsgi.application"

X_FRAME_OPTIONS = "SAMEORIGIN"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"),
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT"),
    }
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = "accounts.User"

# debug toolbar를 허용할 아이피에 대한 allowed ip list
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# SEND_GRID: EMAIL
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"

SENDGRID_API_KEY = env("SENDGRID_API_KEY")

EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_HOST_USER = env("SENDGRID_USERNAME")
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "mysite3" / "static"
]  # Local, 즉 DEBUG=True 일 경우 pipeline 사용
# STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage' # Local, 즉 DEBUG=True 일 경우 pipeline 사용

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"
# TODO: STORAGE: S3
# if DEBUG:
#     STATIC_URL = "/static/"
#     STATIC_ROOT = BASE_DIR / "staticfiles"
#     STATICFILES_DIRS = [
#         BASE_DIR / "mysite3" / "static"
#     ]  # Local, 즉 DEBUG=True 일 경우 pipeline 사용
#     # STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage' # Local, 즉 DEBUG=True 일 경우 pipeline 사용

#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = BASE_DIR / "mediafiles"
# else:
#     # 엑세스 키와 시크릿 키는 다른 파일로 작성, 임포트하여 사용
#     AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")  # 액세스 키
#     AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
#     AWS_REGION = "ap-northeast-2"
#     AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")  # 버킷 이름
#     AWS_S3_CUSTOM_DOMAIN = "%s.s3.%s.amazonaws.com" % (
#         AWS_STORAGE_BUCKET_NAME,
#         AWS_REGION,
#     )

#     DEFAULT_FILE_STORAGE = "mysite3.storages.S3DefaultStorage"
#     STATICFILES_STORAGE = "mysite3.storages.S3StaticStorage"
